name: Build LaTeX document

on: 
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    branches:
      - master


jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document Discrete_Systems
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: lecture_slides/Discrete_Systems/

      - name: Compile LaTeX document for Optimal_Control_of_LTI_systems
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: lecture_slides/Optimal_Control_of_LTI_systems/

      - name: Save Discrete_Systems artifact
        uses: actions/upload-artifact@v1
        with:
          name: Discrete_Systems.pdf
          path: lecture_slides/Discrete_Systems/main.pdf

      - name: Save Optimal_Control_of_LTI_systems artifact
        uses: actions/upload-artifact@v1
        with:
          name: Optimal_Control_of_LTI_systems.pdf
          path: lecture_slides/Optimal_Control_of_LTI_systems/main.pdf

      - name: Update compiled PDFs in git repository
        if: github.event.pull_request.merged == true || (github.event_name == 'push' && github.ref == 'refs/heads/master')
        run: |
          git config --global user.name 'CI PDF compiler'
          git config --global user.email '<>'
          git add lecture_slides/Discrete_Systems/main.pdf
          git add lecture_slides/Optimal_Control_of_LTI_systems/main.pdf
          git commit -m "Update compiled PDFs"
          git push
