name: Build LaTeX document

on: 
  push:
  pull_request:
    branches:
      - master


jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1

      - name: Compile LaTeX document Discrete_Systems
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: lecture_slides/Discrete_Systems/

      - name: Compile LaTeX document for Optimal_Control_of_LTI_systems
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: lecture_slides/Optimal_Control_of_LTI_systems/
