name: Build LaTeX document

on: 
  push:
  pull_request:
    branches:
      - master


jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Discrete_Systems/
#       - name: Save artifact
#         uses: actions/upload-artifact@v1
#         with:
#           name: Discrete_Systems.pdf
#           path: Discrete_Systems/

